### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Noorts** [Noorts/DLSA#1]
- [ ] Architecture.md that can be converted into something for the report (e.g., rust analyzer)
- [x] #2
- [ ] Worker node
  - [ ] Algo implementation (Daniel)
  - [ ] Node registrar interface (Daniel)
- [ ] Registrar + Register Interface for Node (Halli & Enrico)
- [ ] Job Scheduler (Niclas & Paul)
  - [ ] Job Data Format
  - [ ] Job interface for internal format 
  - [ ] Node interface for Job assignment? 
- [x] #4
  - [ ] Support File Types to Internal Format
- [ ] Persistence Layer setup
