### ISSUE TITLE
Tracking: Rust

### ISSUE THREAD

**Issue by DanielVoogsgerd** [Noorts/DLSA#26]
A tracking issue about all problems related to the Rust implementation

To Do
- [x] Convert unit tests to rust
- [x] Setup Benchmarking using Criterion
- [x] Create complete FFI-bindings for Go.
- [x] #27
- [x] Write a Low memory variant of the algorithm
- [x] Use rust version in benchmarker @haraldurbjarni 
- [x] Make vec allocate fallible
- [x] Catch all panics at FFI @haraldurbjarni
